trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: adotest-vg

stages:
#- template: pipeline-templates/addnsg.yaml
- template: ./valandplan.yaml
- template: ./approval.yaml
- template: ./apply.yaml
#- template: pipeline-templates/delnsg.yaml
