trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: adotest-vg

stages:
- template: pipeline-templates/valandplan.yaml
- template: pipeline-templates/approval.yaml
- template: pipeline-templates/apply.yaml
